/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author jengmigo7
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
 
    public static ArrayList<String> strings = new ArrayList<String>();
    ArrayList<String> studn = new ArrayList<String>();
    public static int ctr = 0;
    public static String name1;
    boolean see = true;
    public NewJFrame() {
//raffle s = new raffle(this,true);
        //     s.launch();

        initComponents();
        
     
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src/itam-orig.jpg"));

        } catch (IOException e) {
            e.printStackTrace();
        }
        ImageIcon dimg = new ImageIcon(img.getScaledInstance(logolabel.getWidth(), logolabel.getHeight(), Image.SCALE_SMOOTH));
        logolabel.setIcon(dimg);
        jPanel1.setOpaque(false);      
        jPanel3.setOpaque(false);
        settings.setOpaque(false);
        raffle.setVisible(false);
        list.setVisible(false);
        
        repaint();

    }

    class JTextFieldLimit extends PlainDocument {

        private int limit;
        private int mode;

        JTextFieldLimit(int limit, int mode) {
            super();
            this.limit = limit;
            this.mode = mode;
        }

        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
            if (str == null) {
                return;
            }
            if (mode == 1) {
                for (int i = 0; i < str.length(); i++) {
                    if (str.charAt(i) >= '0' && str.charAt(i) <= '9') {

                    } else {
                        return;
                    }
                }
            }

            if (mode == 2) {
                for (int i = 0; i < str.length(); i++) {
                    if ((str.toUpperCase().charAt(i) >= 'A' && str.toUpperCase().charAt(i) <= 'Z') || (str.toUpperCase().charAt(i) >= '0' && str.toUpperCase().charAt(i) <= '9')) {

                    } else {
                        return;
                    }

                }

            }
            if (mode == 3) {
                for (int i = 0; i < str.length(); i++) {
                    if ((str.toUpperCase().charAt(i) >= 'A' && str.toUpperCase().charAt(i) <= 'Z') || str.charAt(i) == ' ') {

                    } else {
                        return;
                    }
                }
            }
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str.toUpperCase(), attr);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logolabel1 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        raffle = new javax.swing.JButton();
        list = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        logolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(null);

        logolabel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.add(logolabel1);
        logolabel1.setBounds(20, 20, 960, 300);

        settings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                settingsMouseMoved(evt);
            }
        });
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        raffle.setBackground(new java.awt.Color(51, 51, 51));
        raffle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        raffle.setForeground(new java.awt.Color(255, 255, 255));
        raffle.setText("Raffle");
        raffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raffleMouseEntered(evt);
            }
        });
        raffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raffleActionPerformed(evt);
            }
        });

        list.setBackground(new java.awt.Color(51, 51, 51));
        list.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        list.setForeground(new java.awt.Color(255, 255, 255));
        list.setText("List");
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listMouseEntered(evt);
            }
        });
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(raffle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(raffle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        settings.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(settings);
        settings.setBounds(800, 0, 200, 110);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        name.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stud #:");

        studnum.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        studnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studnumFocusLost(evt);
            }
        });
        studnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studnumKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Section :");

        section.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        section.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        section.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sectionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sectionFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studnum, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(name)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(section))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studnum, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 360, 370, 230);

        logolabel.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.add(logolabel);
        logolabel.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (name.getText().isEmpty() || name.getText().matches("\\s+")) {
            hint(name, "(!) Enter your Name.");
            //  name.grabFocus();
//            if (!studnum.getText().isEmpty() || !section.getText().isEmpty() || !section.getText().matches("\\s+")) {
//                name.setText(name.getText());
//            }

        }

        if (studnum.getText().toString().length() < 9 || studnum.getText().isEmpty()) {
            hint(studnum, "(!) Enter your Student no.");

//            if (!name.getText().isEmpty() || !section.getText().isEmpty()||!name.getText().matches("\\s+")) {
//                studnum.grabFocus();
//            }
        }
        if (section.getText().isEmpty()) {
            hint(section, "(!) Enter your Section.");

//            if (!(name.getText().isEmpty() || studnum.getText().isEmpty()||!name.getText().matches("\\s+"))) {
//                section.grabFocus();
//            }
        }
        if ((!section.getText().isEmpty() && !section.getText().matches("\\s+") && !section.getText().equals("(!) Enter your Section.")) && (!name.getText().isEmpty() && !name.getText().equals("(!) Enter your Name.") && !name.getText().matches("\\s+")) && (!studnum.getText().isEmpty()
                && !studnum.getText().equals("(!) Enter your Student no.") && studnum.getText().toString().length() == 9)) {
            boolean ch = false;
            name.setForeground(Color.black);
            section.setForeground(Color.black);
            studnum.setForeground(Color.black);

            //System.out.println(name.getText() + "    " + studnum.getText() + "    " + section.getText());
            for (int i = 0; i < studn.size(); i++) {
                if (studnum.getText().equals(studn.get(i).toString())) {
                    ch = true;
                    break;
                }
            }
            if (ch == true) {
                JOptionPane.showMessageDialog(null, "Student no. Already Exist!", "Already Exist!", JOptionPane.ERROR_MESSAGE);
                name.setText(null);
                section.setText(null);
                studnum.setText(null);
                name.grabFocus();

            } else {
                String temp=name.getText() + "," + studnum.getText() + "," + section.getText();
                strings.add(temp.toLowerCase());
                studn.add(studnum.getText());
                boolean check = false;
                BufferedReader br;
                int cnt = 0;
                try {
                    String word;
                    br = new BufferedReader(new FileReader("listofstudent.csv"));
                    while ((word=br.readLine()) != null) {
                        //word = br.readLine();
                        if (word.toLowerCase().equals(temp.toLowerCase())) {
                            check = false;
                            JOptionPane.showMessageDialog(null, "Person Already Exist!", "Already Exist!", JOptionPane.ERROR_MESSAGE);

                            name.setText(null);
                            section.setText(null);
                            studnum.setText(null);
                            name.grabFocus();
                        } else {
                            check = true;
                        }
                    }
                } catch (IOException ex) {
                    try {
                        FileWriter writer = new FileWriter("Listofstudent.csv", true);

                        String[] st = strings.get(ctr).split("#");
                        ctr += 1;
                        writer.write(strings.get(ctr - 1));
                        writer.write("\r\n");

                        writer.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    JOptionPane.showMessageDialog(null, "Thank you for Attending This Seminar", "Thank you!", JOptionPane.INFORMATION_MESSAGE);
                    name.setText(null);
                    studnum.setText(null);
                    section.setText(null);

                }
                if (check) {
                    try {
                        FileWriter writer = new FileWriter("Listofstudent.csv", true);

                        String[] st = strings.get(ctr).split("#");
                        ctr += 1;
                        writer.write(strings.get(ctr - 1));
                        writer.write("\r\n");

                        writer.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    JOptionPane.showMessageDialog(null, "Thank you for Attending This Seminar", "Thank you!", JOptionPane.INFORMATION_MESSAGE);
                    for (int i = 0; i < strings.size(); i++) {
                        System.out.println(strings.get(i));

                    }
                    name.setText(null);
                    studnum.setText(null);
                    section.setText(null);
                }
            }
        }

        System.out.println(name.getText() + "    " + studnum.getText() + "    " + section.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void studnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studnumFocusGained
        if (studnum.getText().equals("(!) Enter your Student no.")) {
            studnum.setText("");
        }
        studnum.setFont(new Font("Tahoma", Font.PLAIN, 11));
        studnum.setForeground(Color.black);
    }//GEN-LAST:event_studnumFocusGained

    private void sectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sectionFocusGained
        if (section.getText().equals("(!) Enter your Section.")) {
            section.setText("");
        }
        section.setFont(new Font("Tahoma", Font.PLAIN, 11));
        section.setForeground(Color.black);
    }//GEN-LAST:event_sectionFocusGained

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        if (name.getText().equals("(!) Enter your Name.")) {
            name.setText("");
        }
        name.setFont(new Font("Tahoma", Font.PLAIN, 11));
        name.setForeground(Color.black);
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if (name.getText().isEmpty() || name.getText().matches("\\s+")) {
            hint(name, "(!) Enter your Name.");
        }

    }//GEN-LAST:event_nameFocusLost

    private void studnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studnumFocusLost
        if (studnum.getText().toString().length() < 9 || studnum.getText().isEmpty()) {
            hint(studnum, "(!) Enter your Student no.");
        }
    }//GEN-LAST:event_studnumFocusLost

    private void sectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sectionFocusLost
        if (section.getText().isEmpty() || section.getText().matches("\\s+")) {
            hint(section, "(!) Enter your Section.");
        }

    }//GEN-LAST:event_sectionFocusLost

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_nameKeyTyped

    private void studnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studnumKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (studnum.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_studnumKeyTyped

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        new Listings().setVisible(true);
    }//GEN-LAST:event_listActionPerformed

    public void setlist(ArrayList<String> strings) {
        strings = new ArrayList<String>();
        this.strings = strings;
    }

    public ArrayList<String> getlist() {
        return strings;
    }
    private void raffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raffleActionPerformed
        BufferedReader br;
        int cnt = 0;
        try {
            br = new BufferedReader(new FileReader("listofstudent.csv"));
            while (br.readLine() != null) {
                cnt++;
            }
        } catch (IOException ex) {
        }
        System.out.println(cnt);
        if (cnt == 0) {
            JOptionPane.showMessageDialog(null, "Empty Slot!", "Empty!", JOptionPane.ERROR_MESSAGE);
        } else {
            raffle s = new raffle();
            s.launch();
        }


    }//GEN-LAST:event_raffleActionPerformed

    private void settingsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseMoved
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_settingsMouseMoved

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
        // TODO add your handling code here:
        raffle.setVisible(true);
        list.setVisible(true);
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
        // TODO add your handling code here:
        raffle.setVisible(false);
        list.setVisible(false);
    }//GEN-LAST:event_settingsMouseExited

    private void raffleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raffleMouseEntered
        // TODO add your handling code here:
        raffle.setVisible(true);
           list.setVisible(true);
    }//GEN-LAST:event_raffleMouseEntered

    private void listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseEntered
        // TODO add your handling code here:
           raffle.setVisible(true);
        list.setVisible(true);
    }//GEN-LAST:event_listMouseEntered
    public void hint(JTextField j, String s) {
        j.setForeground(new Color(255, 102, 102));
        j.setFont(new Font("Arial", Font.BOLD + Font.ITALIC, 11));
        j.setText(s);
    }

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton list;
    private javax.swing.JLabel logolabel;
    private javax.swing.JLabel logolabel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton raffle;
    private javax.swing.JTextField section;
    private javax.swing.JPanel settings;
    private javax.swing.JTextField studnum;
    // End of variables declaration//GEN-END:variables
}
