/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.List;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author jengmigo7
 */
public class raffle extends javax.swing.JDialog {

    /**
     * Creates new form raffle
     */
    List wi = new List();
    List li = new List();
    static Timer timer, t1;
    static int interval, randtimer;

    public raffle() {

        initComponents();
        setLocationRelativeTo(null);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        // this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

        name.setHorizontalAlignment(SwingConstants.CENTER);
        name.setVerticalAlignment(SwingConstants.CENTER);
        section.setHorizontalAlignment(SwingConstants.CENTER);
        section.setVerticalAlignment(SwingConstants.CENTER);
        studnum.setHorizontalAlignment(SwingConstants.CENTER);
        studnum.setVerticalAlignment(SwingConstants.CENTER);
        cong.setHorizontalAlignment(SwingConstants.CENTER);
        cong.setVerticalAlignment(SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cd = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        studnum = new javax.swing.JLabel();
        section = new javax.swing.JLabel();
        cong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Start!");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cd.setBackground(new java.awt.Color(51, 51, 51));
        cd.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        cd.setForeground(new java.awt.Color(255, 255, 255));
        cd.setText("5");

        name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));

        studnum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studnum.setForeground(new java.awt.Color(255, 255, 255));

        section.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        section.setForeground(new java.awt.Color(255, 255, 255));

        cong.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        cong.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))
                    .addComponent(cd))
                .addGap(65, 65, 65))
            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(section, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studnum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cd)
                .addGap(18, 18, 18)
                .addComponent(cong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studnum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        if(!studnum.getText().equals("")){
         try {
             
             // wi= new List();
             // li = new List();
              wi.removeAll();
              li.removeAll();
              System.out.println(wi.getItemCount());
                FileWriter fw = new FileWriter("win.csv",true);
                fw.write(studnum.getText()+"\n");
                fw.close();
            } catch (IOException ex) {
            }
        }
         int delay = 100;
        int period = 1000;
        timer = new Timer();
        t1 = new Timer();
        interval = 5;
        randtimer = 500;
        jButton1.setVisible(false);
        BufferedReader br,wir;
        String word;
        String st;
        try {
            wir = new BufferedReader(new FileReader("win.csv"));
            while ((st = wir.readLine()) != null) {
                wi.add(st);
            }
            wir.close();
        } catch (Exception ex) {
            
        }
        try {
            
            br = new BufferedReader(new FileReader("listofstudent.csv"));
            while ((word = br.readLine()) != null) { 
                int i =0;
                if (wi.getItemCount() == 0) {
                        li.add(word);
                      
                } else {
                    boolean ok = true;
                    for( String in : wi.getItems()){
                       String []temp= word.split(",");
                        System.out.println(Integer.parseInt(in)+" | "+Integer.parseInt(temp[1]));
                        if ((Integer.parseInt(in))==(Integer.parseInt(temp[1]))) {
                            ok = false;
                            break;
                        }
                  
                    }
                    if(ok){li.add(word);}
                }
            }
            br.close();
        } catch (IOException ex) {
        }

        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                cd.setText("" + setInterval());

            }
        }, delay, period);
        t1.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                //name.setText("" + setrandtimer());

                String data[] = li.getItem(setrandtimer()).toString().split(",");
                name.setText(data[0].toUpperCase());
                studnum.setText(data[1].toUpperCase());
                section.setText(data[2].toUpperCase());
               
            }
        }, 100, 100);

        if (setInterval() == 0) {
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private final int setInterval() {
        if (interval == 1) {
            cong.setText("Congratulations !");
            
            timer.cancel();
            
        } else {
            cong.setText("");
        }

        return --interval;
    }

    private final int setrandtimer() {
        Random r = new Random();
        if (interval == 0) {
            jButton1.setVisible(true);            
            t1.cancel();
           
        }
        return r.nextInt(li.getItemCount());
    }

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(raffle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(raffle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(raffle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(raffle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                raffle dialog = new raffle();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cd;
    private javax.swing.JLabel cong;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel section;
    private javax.swing.JLabel studnum;
    // End of variables declaration//GEN-END:variables
}
